### ISSUE TITLE
Updates required per SUPEE-6788?

### ISSUE THREAD

**Issue by jkowens** [jkowens/magento-jobqueue#12]
Need to make sure this module meets the latest security guidelines. See [SUPEE-6788](http://magento.com/security/patches/supee-6788-technical-details).

**Comment by MrGekko** [comment]
I dont think that this is a issue... I use the module with 1.9.2.2 and everything is working fine... But I dont know if the working of the module is enough to say that it meets the guidelines.

**Comment by jkowens** [comment]
Cool, do you have "Enable Admin routing compatibility mode" set to disabled under System > Configuration > Admin > Security? That was the main item I was concerned about.

**Comment by jkowens** [comment]
It looks like this module is in good shape.
