### ISSUE TITLE
Publishing this project on packagist.org

### ISSUE THREAD

**Issue by elvetemedve** [jkowens/magento-jobqueue#15]
When someone wants to install this Magento extension via Composer, it will not be possible by running `composer require jkowens/magento-jobqueue`. That's because Composer reads available packages from **packagist.org** repository. So this Git repo should be submitted to there in order to make the package available. In addition each new version should be tagged, that way packagist can automatically publish new versions.

Things to do:
- create a Git **tag 0.5.0** from the current master branch
- create an account on **packagist.org** and **register** this Git repository
- **enable auto update** to let packagist publish future releases automatically

I've created a fork and published it here: https://packagist.org/packages/elvetemedve/magento-jobqueue
I'll remove it as soon as the original package is available on packagist.

**Comment by jkowens** [comment]
Thanks for these instructions! I've just added this project to Packagist 👍

**Comment by elvetemedve** [comment]
Thanks for acting quickly.

I still need to wait for the **[seatgeek/djjob](https://github.com/seatgeek/djjob/issues/44)** package to be released. Because now Composer refuse to install it, except if I lower the minimum stability to _dev_. 
Until then I won't delete my fork, but I marked the package as abandoned.
