### ISSUE TITLE
Locked Job.

### ISSUE THREAD

**Issue by iuribertto** [jkowens/magento-jobqueue#19]
Hello,

I have been using your module for some time and it is great, but in recent days I am getting the following message when my cron is called:
[2017-10-23T17:48:07+00:00] [JOB] attempting to acquire lock for job::56 on host::webserver3 pid::15857

My job gets situation "In Progress" forever, have you ever come across this problem?

Thank you very much.

**Comment by jkowens** [comment]
That logged message looks to be standard output from DJJob, the underlying queuing library:

https://github.com/seatgeek/djjob/blob/f3ce62f9ffd74e695cb20858d3269a81a70f25e3/DJJob.php?utf8=%E2%9C%93#L379

My guess is that possibly something is failing with the job itself. I just updated DJJob to the latest version, so maybe that will help you diagnose the issue. It looks like there may have been some commits related to error handling.

**Comment by jkowens** [comment]
Closing for now. Feel free to reopen if you find more details. I would suggest adding more logging statements to your job to get a better idea of what's going on.
